### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by defidead** [HITMANek210/Aimware-Online-Radar#10]
[2023-04-25 23:54:38,552] ERROR in app: Exception on /imgdata [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ubuntu/Aimware-Online-Radar/flaskapp.py", line 22, in imgdata
    data_to_show = base64.b64decode(request.args.get('data')).decode("utf-8")
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (997) cannot be 1 more than a multiple of 4

**Comment by defidead** [comment]
[2023-04-26 00:42:15,191] ERROR in app: Exception on /imgdata [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ubuntu/Aimware-Online-Radar/flaskapp.py", line 22, in imgdata
    data_to_show = base64.b64decode(request.args.get('data')).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 118: invalid continuation byte
Invalid session DULIdAUBBP2ZInXEAAAT (further occurrences of this error will be logged with level INFO)

**Comment by defidead** [comment]
[2023-04-26 00:45:33,778] ERROR in app: Exception on /imgdata [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ubuntu/Aimware-Online-Radar/flaskapp.py", line 22, in imgdata
    data_to_show = base64.b64decode(request.args.get('data')).decode("utf-8")
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by HITMANek210** [comment]
Make sure you are using the newest version of the scripts (app.py, map.lua)
Try to change app.config['SECRET_KEY'] in app.py. Restarting the server also may help.

If none of this works reinstall the script and all of the packages.

**Comment by defidead** [comment]
notwork i restart and reinstall but get this erro again ,did you use python2?

**Comment by defidead** [comment]
i print data and encode `{"local_player":true,"map":"de_mirage","players":[{"player_x":"753","player_y":"683","team_num":"2","player_name":"гЃЁаe8Ю8о88^8‚"В'Ж–W%ц†VЗF‚#ў#"В'G&6U‚#ў#s""В'G&6U’#ў#cs'ТЗІ'Ж–W%ч‚#ў#S“’"В'Ж–W%ч’#ў#s’"В'FVХцзVТ#ў#2"В'Ж–W%цжЦR#ў$VЖЖ–чB"В'Ж–W%ц†VЗF‚#ў#"В'G&6U‚#ў#3ѓr"В'G&6U’#ў#cR'ТЗІ'Ж–W%ч‚#ў#SB"В'Ж–W%ч’#ў#s“b"В'FVХцзVТ#ў#2"В'Ж–W%цжЦR#ў%vЗB"В'Ж–W%ц†VЗF‚#ў#"В'G&6U‚#ў#cr"В'G&6U’#ў#c“"'ТЗІ'Ж–W%ч‚#ў#3c2"В'Ж–W%ч’#ў#ccR"В'FVХцзVТ#ў#""В'Ж–W%цжЦR#ў$vVч&vR"В'Ж–W%ц†VЗF‚#ў#"В'G&6U‚#ў#3‚"В'G&6U’#ў#cSr'ТЗІ'Ж–W%ч‚#ў#sB"В'Ж–W%ч’#ў#cc’"В'FVХцзVТ#ў#""В'Ж–W%цжЦR#ў$†'fW’"В'Ж–W%ц†VЗF‚#ў#"В'G&6U‚#ў#c“’"В'G&6U’#ў#cs'ТЗІ'Ж–W%ч‚#ў#sr"В'Ж–W%ч’#ў#csb"В'FVХцзVТ#ў#""В'Ж–W%цжЦR#ў%—W&’"В'Ж–W%ц†VЗF‚#ў#"В'G&6U‚#ў#c“’"В'G&6U’#ў#cѓ'ТЗІ'Ж–W%ч‚#ў#S3B"В'Ж–W%ч’#ў#ѓB"В'FVХцзVТ#ў#2"В'Ж–W%цжЦR#ў$Ж''’"В'Ж–W%ц†VЗF‚#ў#"В'G&6U‚#ў#SSr"В'G&6U’#ў#cCb'ТЗІ'Ж–W%ч‚#ў#Sѓ""В'Ж–W%ч’#ў#s’"В'FVХцзVТ#ў#""В'Ж–W%цжЦR#ў$g&жІ"В'Ж–W%ц†VЗF‚#ў#"В'G&6U‚#ў#Ss""В'G&6U’#ў#sC'ТЗІ'Ж–W%ч‚#ў#SR"В'Ж–W%ч’#ў#ѓ""В'FVХцзVТ#ў#2"В'Ж–W%цжЦR#ў$ЖЖVв"В'Ж–W%ц†VЗF‚#ў#"В'G&6U‚#ў#cC2"В'G&6U’#ў#c#2'ХТВ&&цЦ"#§І&&цЦ%ч‚#¦fЗ6RВ&&цЦ%ч’#¦fЗ6RВ'ЖзFVB#¦fЗ6WЧ`notice has something wrong from aimware send

**Comment by defidead** [comment]
i print data and encode` {"local_player":true,"map":"de_mirage","players":[{"player_x":"753","player_y":"683","team_num":"2","player_name":"гЃЁаe8�Ю8�о8��8�^8�‚"В'�Ж�–W%ц†V�ЗF‚#ў#���"В'G&�6U‚#ў#s�""В'G&�6U’#ў#cs�'ТЗІ'�Ж�–W%ч‚#ў#S“’"В'�Ж�–W%ч’#ў#s�’"В'FV�ХцзVТ#ў#2"В'�Ж�–W%цж�ЦR#ў$VЖЖ–чB"В'�Ж�–W%ц†V�ЗF‚#ў#���"В'G&�6U‚#ў#3ѓr"В'G&�6U’#ў#c�R'ТЗІ'�Ж�–W%ч‚#ў#S�B"В'�Ж�–W%ч’#ў#s“b"В'FV�ХцзVТ#ў#2"В'�Ж�–W%цж�ЦR#ў%v�ЗB"В'�Ж�–W%ц†V�ЗF‚#ў#���"В'G&�6U‚#ў#c�r"В'G&�6U’#ў#c“"'ТЗІ'�Ж�–W%ч‚#ў#3c2"В'�Ж�–W%ч’#ў#ccR"В'FV�ХцзVТ#ў#""В'�Ж�–W%цж�ЦR#ў$vVч&vR"В'�Ж�–W%ц†V�ЗF‚#ў#���"В'G&�6U‚#ў#3�‚"В'G&�6U’#ў#cSr'ТЗІ'�Ж�–W%ч‚#ў#s�B"В'�Ж�–W%ч’#ў#cc’"В'FV�ХцзVТ#ў#""В'�Ж�–W%цж�ЦR#ў$†�'fW’"В'�Ж�–W%ц†V�ЗF‚#ў#���"В'G&�6U‚#ў#c“’"В'G&�6U’#ў#cs�'ТЗІ'�Ж�–W%ч‚#ў#s�r"В'�Ж�–W%ч’#ў#csb"В'FV�ХцзVТ#ў#""В'�Ж�–W%цж�ЦR#ў%—W&’"В'�Ж�–W%ц†V�ЗF‚#ў#���"В'G&�6U‚#ў#c“’"В'G&�6U’#ў#cѓ�'ТЗІ'�Ж�–W%ч‚#ў#S3B"В'�Ж�–W%ч’#ў#ѓ�B"В'FV�ХцзVТ#ў#2"В'�Ж�–W%цж�ЦR#ў$Ж�''’"В'�Ж�–W%ц†V�ЗF‚#ў#���"В'G&�6U‚#ў#SSr"В'G&�6U’#ў#cCb'ТЗІ'�Ж�–W%ч‚#ў#Sѓ""В'�Ж�–W%ч’#ў#s�’"В'FV�ХцзVТ#ў#""В'�Ж�–W%цж�ЦR#ў$g&�жІ"В'�Ж�–W%ц†V�ЗF‚#ў#���"В'G&�6U‚#ў#Ss""В'G&�6U’#ў#sC�'ТЗІ'�Ж�–W%ч‚#ў#S�R"В'�Ж�–W%ч’#ў#ѓ�""В'FV�ХцзVТ#ў#2"В'�Ж�–W%цж�ЦR#ў$�ЖЖVв"В'�Ж�–W%ц†V�ЗF‚#ў#���"В'G&�6U‚#ў#cC2"В'G&�6U’#ў#c#2'ХТВ&&цЦ"#§І&&цЦ%ч‚#¦f�З6RВ&&цЦ%ч’#¦f�З6RВ'�Ж�зFVB#¦f�З6WЧ `and i tey print lua data i notce lua data is right
