### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by Pingfan1337** [HITMANek210/Aimware-Online-Radar#12]
It is stuck on here when I run it
`[2023-06-24 01:11:55 +0800] [4798] [INFO] Listening at: http://0.0.0.0:80 (4798)
[2023-06-24 01:11:55 +0800] [4798] [INFO] Using worker: eventlet
[2023-06-24 01:11:55 +0800] [4801] [INFO] Booting worker with pid: 4801
`

**Comment by Pingfan1337** [comment]
'[2023-06-24 01:21:01 +0800] [4881] [ERROR] Error handling request /socket.io/?EIO=4&transport=websocket&sid=VksW4smiErOBerjyAAAK
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 44, in __call__
    start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 607, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 408, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 637, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
