### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by Nakano39** [HITMANek210/Aimware-Online-Radar#8]
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 5, in <module>
    from gunicorn.app.wsgiapp import run
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 38
    print("\nError: %s" % str(e), file=sys.stderr)
                                      ^
SyntaxError: invalid syntax

**Comment by HITMANek210** [comment]
Try to update all your python packages and the python itself.
If it's just gunicorn related issue try to uninstall gunicorn and install it using this command:
`pip install https://github.com/benoitc/gunicorn/archive/refs/heads/master.zip#egg=gunicorn==20.1.0`
